### ISSUE TITLE
MAVlink information needs to be updated to support both RTSP and RTPUDP depending of the video stream 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/mavlink-camera-manager#38]
https://github.com/patrickelectric/mavlink-camera-manager/blob/ed527463feef50617012ec88106a04035542be86/src/mavlink/mavlink_camera.rs#L537

**Comment by joaoantoniocardoso** [comment]
https://mavlink.io/en/messages/common.html#VIDEO_STREAM_TYPE
