### ISSUE TITLE
QGC integration is failing

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/mavlink-camera-manager#57]
Changes on QGC control does not affect v4l controls

**Comment by joaoantoniocardoso** [comment]
The part needed for the QGC UI buttons and controls is fixed by #67 and #72, but there are still mavlink messages missing on our side that are sent by QGC, although it seems to be working fine without them.

**Comment by patrickelectric** [comment]
Can you inform what kind of messages ? Are messages that are important for us or are just generic vehicle messages that we are ignoring ?

**Comment by joaoantoniocardoso** [comment]
@patrickelectric these are the messages not being handled:
- PARAM_EXT_REQUEST_READ ([ #320 ](https://mavlink.io/en/messages/common.html#PARAM_EXT_REQUEST_READ))
- PARAM_EXT_REQUEST_LIST ([ #321 ](https://mavlink.io/en/messages/common.html#PARAM_EXT_REQUEST_LIST))

**Comment by joaoantoniocardoso** [comment]
After implementing 320 and 321, there is another being requested:
- MAV_CMD_REQUEST_VIDEO_STREAM_STATUS ([2505](https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_VIDEO_STREAM_STATUS) )

**Comment by joaoantoniocardoso** [comment]
After #107, we should do a big test to check if anything else is missing. 

From my tests, there is still one message missing, which asks for the value of a control, but QGC ends up asking for the value of all controls when it gets no answer for that message.

**Comment by patrickelectric** [comment]
> After implementing 320 and 321, there is another one being requested by QGC:
> 
> * MAV_CMD_REQUEST_VIDEO_STREAM_STATUS ([2505](https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_VIDEO_STREAM_STATUS) )

Just check QGC source code

**Comment by joaoantoniocardoso** [comment]
> > After implementing 320 and 321, there is another one being requested by QGC:
> > 
> > * MAV_CMD_REQUEST_VIDEO_STREAM_STATUS ([2505](https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_VIDEO_STREAM_STATUS) )
> 
> Just check QGC source code

What a great idea, I'll do that right away :1st_place_medal:
